version: '3.4'

networks:
  integration-test:

services:
  expense_integration_test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - $PWD:/go/src/expense
    depends_on:
      - expense_mock_db
    networks:
      - integration-test
  expense_mock_db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: expenses
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: expenses
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test